### ISSUE TITLE
In NotoSansSiddham-Regular, reph ra is not above base.

### ISSUE THREAD

**Issue by ijaradnam** [notofonts/siddham#1]
### Title 
In NotoSansSiddham-Regular, reph ra is not above base.

### Font 
 'NotoSansSiddham-Regular.otf'.

### Issue
In horizontal writing, letters starting with ra and other letters are written below the same reference line. This eliminates the features of reph ra.

**Comment by Dailoan7777** [comment]
_

**Comment by Dailoan7777** [comment]
Consolas
