### ISSUE TITLE
'ss03' does not affect `seed_va_c_l_m_d_y_aiMatrasidd`

### ISSUE THREAD

**Issue by dscorbett** [notofonts/siddham#15]
### Font
NotoSansSiddham-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/siddham/releases/tag/NotoSansSiddham-v2.003
Date: 2022-09-12

### Font version
Version 2.003

### Issue
When the glyph `seed_va_c_l_m_d_y_aiMatrasidd` is enabled by 'ss04' “Seed syllables (shuji)”, 'ss03' “Large AI and AU matra (warabi ten)” has no effect on the <i>-ai</i> vowel sign part of the glyph. Should it?

### Character data
𑖪𑖿𑖓𑖿𑖩𑖿𑖦𑖿𑖟𑖿𑖧𑖹
U+115AA SIDDHAM LETTER VA
U+115BF SIDDHAM SIGN VIRAMA
U+11593 SIDDHAM LETTER CA
U+115BF SIDDHAM SIGN VIRAMA
U+115A9 SIDDHAM LETTER LA
U+115BF SIDDHAM SIGN VIRAMA
U+115A6 SIDDHAM LETTER MA
U+115BF SIDDHAM SIGN VIRAMA
U+1159F SIDDHAM LETTER DA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115B9 SIDDHAM VOWEL SIGN AI

### Screenshots
![𑖪𑖿𑖓𑖿𑖩𑖿𑖦𑖿𑖟𑖿𑖧𑖹](https://user-images.githubusercontent.com/1124347/189766316-7cef5400-2236-4e29-9fa6-a778f9b054db.png)
Compare with just 'ss03':
![𑖪𑖿𑖓𑖿𑖩𑖿𑖦𑖿𑖟𑖿𑖧𑖹](https://user-images.githubusercontent.com/1124347/189766581-62d5e21e-363e-495f-84aa-24ad7610bf6a.png)

**Comment by simoncozens** [comment]
I think this is fine; seed syllables are a distinct form, and it's OK for them not to interact with other stylistic sets.
