### ISSUE TITLE
`seed_ta_h_iiMatra_ma_msidd` uses the wrong vowel sign

### ISSUE THREAD

**Issue by dscorbett** [notofonts/siddham#16]
### Font
NotoSansSiddham-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/siddham/releases/tag/NotoSansSiddham-v2.003
Date: 2022-09-12

### Font version
Version 2.003

### Issue
'ss04' “Seed syllables (shuji)” forms the glyph `seed_ta_h_iiMatra_ma_msidd` out of various character sequences that all include U+115B0 SIDDHAM VOWEL SIGN I, whereas they should instead include U+115B1 SIDDHAM VOWEL SIGN II.

### Character data
𑖝𑖰𑖮𑖦𑖿𑖦
U+1159D SIDDHAM LETTER TA
U+115B0 SIDDHAM VOWEL SIGN I
U+115AE SIDDHAM LETTER HA
U+115A6 SIDDHAM LETTER MA
U+115BF SIDDHAM SIGN VIRAMA
U+115A6 SIDDHAM LETTER MA

### Screenshots
![𑖝𑖰𑖮𑖦𑖿𑖦](https://user-images.githubusercontent.com/1124347/189768499-5c326eed-61fe-45bb-861d-dcacceaf5ddc.png)
Compare without 'ss04':
![𑖝𑖰𑖮𑖦𑖿𑖦](https://user-images.githubusercontent.com/1124347/189768502-e0aa8b63-b90e-42f8-9aa3-0ecca01a1f92.png)

**Comment by simoncozens** [comment]
Yep, that seems to be a typo in the ruleset. Presuming that the correct input sequence should be ta-ha-ii-ma-m, I have fixed it.
