### ISSUE TITLE
'ss05' renders vowel signs with /rya/ incorrectly

### ISSUE THREAD

**Issue by mandel59** [notofonts/siddham#19]
### Title 
  'ss05' renders vowel signs with /rya/ incorrectly

### Font 
  NotoSansSiddham-Regular.ttf

### Where the font came from, and when
  Site: https://github.com/notofonts/siddham/releases/tag/NotoSansSiddham-v2.003
  Date: 2022-09-15

### Font Version
  Version 2.003

### OS name and version
  macOS Monterey version 12.6

### Application name and version
  hb-view, Firefox

### Issue

'ss05' alters the form of the /rya/ character, but vowel signs are not alterd and rendered incorrectly.

### Character data

Characters `rya ryā ryi ryī ryu ryū rye ryo`:

```
𑖨𑖿𑖧𑖨𑖿𑖧𑖯𑖨𑖿𑖧𑖰𑖨𑖿𑖧𑖱𑖨𑖿𑖧𑖲𑖨𑖿𑖧𑖳𑖨𑖿𑖧𑖸𑖨𑖿𑖧𑖺
```

```
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115AF SIDDHAM VOWEL SIGN AA
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115B0 SIDDHAM VOWEL SIGN I
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115B1 SIDDHAM VOWEL SIGN II
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115B2 SIDDHAM VOWEL SIGN U
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115B3 SIDDHAM VOWEL SIGN UU
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115B8 SIDDHAM VOWEL SIGN E
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+115A7 SIDDHAM LETTER YA
U+115BA SIDDHAM VOWEL SIGN O
```

#### Harfbuzz hb-view rendering

```
hb-view --font-file=NotoSansSiddham-Regular.ttf --features=ss05 --text-file=input.txt --output-file=out.png
```

![out](https://user-images.githubusercontent.com/1079715/190217392-67b57e50-755f-415e-8ba9-a877776234ec.png)

#### Firefox

<img width="1127" alt="スクリーンショット 2022-09-15 2 02 40" src="https://user-images.githubusercontent.com/1079715/190217520-2c751dd9-89d1-41c0-a1eb-5fabbe7ac3b3.png">

Rendered with Bonji Input (https://mandel59.github.io/bonji-input/)

**Comment by simoncozens** [comment]
I've made ss05 do something vaguely sensible with ryu, but I feel like there's not much to distinguish between ryu with ss05 and ryu with ss01.

Default:
![shape](https://github.com/notofonts/siddham/assets/106728/b0d07a97-5959-4f3b-8c70-d09738b9d990)

ss05:
![shape](https://github.com/notofonts/siddham/assets/106728/36491f69-8592-4b21-a716-1d591f2d1d83)

ss01:
![shape](https://github.com/notofonts/siddham/assets/106728/d0eab728-c47f-4615-abb2-f6780184b183)
