### ISSUE TITLE
Font encode problems in Fontlab 8 software

### ISSUE THREAD

**Issue by caominhsg** [notofonts/siddham#20]
The correct 
![image](https://user-images.githubusercontent.com/69635655/192086208-3a995f83-7552-42ad-80bc-114af46c8508.png)

Encoding problem in Fontlab 8
![image](https://user-images.githubusercontent.com/69635655/192086235-6ca29123-e2c5-4d74-bcc9-0f5c2b03aa28.png)

**Comment by simoncozens** [comment]
I'm not sure I understand this - is it a bug in Fontlab 8's shaping?

**Comment by simoncozens** [comment]
I don't have enough information to take this forward, but my suspicion is that the problem lies with Fontlab and not this font. You could try their forum.
