### ISSUE TITLE
Correction in glyph of jña in Siddham 

### ISSUE THREAD

**Issue by sridatta1** [notofonts/siddham#3]
### Title 
Glyph of jña in Siddham
### Font 
Noto Sans Siddham

### Where the font came from, and when
  > For example:
Noto Sans Siddham
https://fonts.google.com/download?family=Noto%20Sans%20Siddham
  >   Date: 2022-06-22 (preferred format)

### OS name and version
Ubuntu 18.04

### Issue
The existing glyph of jña has the regular form of ña, similar to Sharada, Nagari and other north Indic scripts, jña would be special form
  1. Steps to reproduce
𑖕𑖿𑖗 
  3. Observed results
![text (1)](https://user-images.githubusercontent.com/23263723/175064569-2a22e7d5-3713-4b2e-ac28-0e60fd449577.png)

  5. Expected results
  Similar to
![image](https://user-images.githubusercontent.com/23263723/175064834-e30bc72b-d3bc-4d14-afce-9851346a1dc8.png)

  7. Additional information 
  jñā in horyuji manuscript.

![image](https://user-images.githubusercontent.com/23263723/175065008-eb84ac0c-98ce-44a3-8065-7eab3bbf6957.png)
From Fig 14 of L2/12-234R Siddham proposal
![image](https://user-images.githubusercontent.com/23263723/175067530-b05136fa-7edd-42ba-87ef-72759696442e.png)

From fig 45 of L2/12-234R
![image](https://user-images.githubusercontent.com/23263723/175065208-9fe642b8-ccd3-4656-83ce-99cc765cd505.png)

From Fig 39 of L2/12-234R
![image](https://user-images.githubusercontent.com/23263723/175066609-57a16796-45c2-4345-8272-bb1921fe72e5.png)

![image](https://user-images.githubusercontent.com/23263723/175066911-8f7da80c-228c-4a5e-8a34-516d1e0b5173.png)
(https://gallica.bnf.fr/ark:/12148/btv1b8301004s.r=sanskrite%20siddham?rk=85837;2#)
See http://www.visiblemantra.org/alphabet.html
![image](https://user-images.githubusercontent.com/23263723/175067161-9fbe5bbe-ef92-417d-907a-38c16aa6c240.png)
http://www.siddham.org/yuan1/mantra/g_mantra_heart2.html

ApDevaSiddham font
![image](https://user-images.githubusercontent.com/23263723/175067936-37db07e0-e4e8-449e-8de7-52dd61e3f3a4.png)
Heart sutra ( from Central Asia)
![image](https://user-images.githubusercontent.com/23263723/175068312-afbddcbe-95cc-4c99-bb71-1cb7f6d499e9.png)
https://commons.wikimedia.org/wiki/File:Prajnyaapaaramitaa_Hridaya_Pel.sogd.jpg
After expert opinion, the glyph can be changed.
Cc @tosche for your opinion based on your sources.
Similarly the glyph for jjña needs to be added.

### Character data
𑖕𑖿𑖗  𑖕𑖿𑖕𑖿𑖗

**Comment by Tosche** [comment]
My source is _Bonji Taikan_ (梵字大鑑) which shows the jna in the form of default Noto Sans, and the 3-like shape as the alternate form. I'm sure the default/alternate status varies from source to source, and I am 
It's already included in Noto as the alternate, so at least redrawing won't be necessary.

![IMG_3598](https://user-images.githubusercontent.com/5482424/176159130-1f9e3bed-ea9e-4244-9ac5-2ff231b2d34e.jpeg)
![IMG_3599](https://user-images.githubusercontent.com/5482424/176159141-429a2ae8-9993-427f-ab4e-01519ab41c5f.jpeg)
(Sorry for the blur but I think you get the idea)

Another source is 梵字悉曇章 from 1735, found in the National Diet Library.
![スクリーンショット 2022-06-28 11 51 15](https://user-images.githubusercontent.com/5482424/176162069-11d148be-3b16-4775-b448-22264f5041ae.png)

**Comment by sridatta1** [comment]
Thank you,
In the the running texts  which you have come across ( and not in charts of conjuncts), which form of jña commonly occurs?
Is the default form of Noto Sans font found there?

**Comment by Tosche** [comment]
I have only checked these tables; Japanese monks uses to make tons of these so-called exhaustive list of possible syllables as part of their Buddhist practice, so we have plenty of tables which I thought was enough. I haven't associated the 3-like forms in my brain much (to me, it felt more like jṇa that's mis-transcribed), but I'm no specialist in Sanskrit.

**Comment by sridatta1** [comment]
Thanks, for confirming that existing forms in Noto Sans are not incorrect.

**Comment by sridatta1** [comment]
> to me, it felt more like jṇa that was mis-transcribed.
It is part of evolution from Brahmi, most other North Indic scripts too have 3-like forms.
I can provide the images later.

**Comment by simoncozens** [comment]
> It's already included in Noto as the alternate, so at least redrawing won't be necessary.

I can't seem to find it! What's the glyph name?

**Comment by dscorbett** [comment]
The other glyph is `seed_ja_nnsidd`, available by applying 'ss04' to <U+11595, U+115BF, U+1159C> <i>jṇa</i> (not <i>jña</i>):
![𑖕𑖿𑖜](https://user-images.githubusercontent.com/1124347/189721587-6fb82fd3-386c-4d84-af4a-5e93b5e6c782.png)
